// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"Community_Basic","status":true,"description":"Plugin used to set basic parameters.","parameters":{"cacheLimit":"20","screenWidth":"816","screenHeight":"624","changeWindowWidthTo":"","changeWindowHeightTo":"","renderingMode":"auto","alwaysDash":"off"}},
{"name":"MadeWithMv","status":false,"description":"Show a Splash Screen \"Made with MV\" and/or a Custom Splash Screen before going to main screen.","parameters":{"Show Made With MV":"true","Made with MV Image":"MadeWithMv","Show Custom Splash":"false","Custom Image":"","Fade Out Time":"120","Fade In Time":"120","Wait Time":"160"}},
{"name":"Drill_EventOtherCondition","status":true,"description":"[v1.1]        物体 - 事件页出现条件","parameters":{}},
{"name":"Drill_EventDuplicator","status":true,"description":"[v1.6]        物体 - 事件复制器","parameters":{}},
{"name":"Drill_EventSelfSwitch","status":true,"description":"[v1.7]        物体 - 独立开关","parameters":{}}
];
